### ISSUE TITLE
[Feature]: Remove contact developer profile picture and link to GitHub

### ISSUE THREAD

**Issue by ttebify** [ttebify/content-caddy#12]
The current extension includes a profile picture and link to contact the developer. This is not necessary and can be replaced with a link to the project's GitHub page. This issue will focus on removing the contact developer profile picture and updating the link to the GitHub page.

**Comment by mud1tx** [comment]
Hello, I am trying to fix this issue but I am not able to run this code It is showing an error.

![Screenshot (356)](https://user-images.githubusercontent.com/89539376/230657689-47ebe5cc-d3ec-4f9e-8b2e-2b0054420cfc.png)

What should I do?

**Comment by mud1tx** [comment]
I just clone and just run 2 commands 
npm install
npm run dev as npm dev was not working

**Comment by Priyanko9** [comment]
Hello,i had replaced the image with github link.I am raising a PR
<img width="749" alt="Screenshot 2023-04-08 at 12 33 26 AM" src="https://user-images.githubusercontent.com/11428345/230663590-ceacf0ac-0e65-49a5-8d1f-7a9d57476a21.png">

**Comment by ttebify** [comment]
Hi @mud1tx thank you for your interest to contribute. We currently use yarn as our package manager

You install yarn with npm using this command `npm install -g yarn`

After you have installed yarn globally, in the project root folder, run `yarn install` then `yarn dev` to build for development or `yarn build` you can refer to the readme file for reference.

**Comment by ttebify** [comment]
> I just clone and just run 2 commands npm install npm run dev as npm dev was not working

Hello @mud1tx, I noticed your message now. Have you already managed to complete the task? To resolve the error, you may need to update your repository. A pull request (#17) was submitted to fix the issue. I will assign this task to you since you initially took it up.

@Priyanko9, great job on the pull request. However, as Mudit took up the task first, would you mind working on other open issues?

**Comment by ttebify** [comment]
I will be marking this as done ✅  huge thanks to @Priyanko9
