### ISSUE TITLE
[BUG]: Disable tooltip on text inputs

### ISSUE THREAD

**Issue by ttebify** [ttebify/content-caddy#16]
**Describe the bug**

Currently, the tooltip appears when the user hovers over text inputs. This is not useful for the user, as the extension is designed to save web content for future use. Disabling the tooltip on text inputs would make the user interface more intuitive and less distracting.

**To Reproduce**
1. Install the Content Caddy extension in your browser.
2. Visit any website that has a text input field.
3. Type in some text into the input field and highlight
4. Observe that the tooltip appears, which is not the intended behaviour.

**Expected behaviour**
The tooltip should not appear on text inputs

**Comment by Shweta112233** [comment]
Is this specific to any browser/Operating System ? I
 was not able to reproduce this issue on my unix system in brave browser.
What i did to reproduce the issue ? ->  on youtube tried to add a comment.

**Comment by ttebify** [comment]
Hi @Shweta112233 I may have to look into this again. I was testing on edge an it seems to have that problem.
