### ISSUE TITLE
[FEATURE]: Assistance with branding of Content Caddy, including logo and store listing images.

### ISSUE THREAD

**Issue by ttebify** [ttebify/content-caddy#37]
**Is your feature request related to a problem? Please describe.**
Currently, the Content Caddy extension on the Microsoft web store has a plain design with no cover image or branding. We would like to improve the branding of the extension to make it stand out more.

Visit the extension page on the Microsoft web-store here: https://microsoftedge.microsoft.com/addons/detail/icblaofpjceadeagkejnojmknpbkhpdd.

**Describe the solution you'd like**
We are seeking assistance from anyone who is willing to help us with this challenge. We would like someone to create a new logo, choose branding colours, and design images that will make the extension more visually appealing and recognisable. Thank you! 🤩

**Comment by 3simransharma** [comment]
Hey! I can do all these designs, I'm also a graphic designer. Can you assign this task to me?

**Comment by ttebify** [comment]
Sweet 🤩. Thank you @3simransharma  Are you available on twitter?

**Comment by 3simransharma** [comment]
> Sweet 🤩. Thank you @3simransharma Are you available on twitter? If so, I would like to connect with you to discuss the designs we will be needing and explore how your contributions could be valuable.

Sorry but currently I don't have a twitter account, I do have Linkedin account. which is on my github profile.

**Comment by Vistech-Tolnez** [comment]
Sorry for showing up late.

I'm interested in CC and I'll love to contribute to the graphics content of this project!
